### ISSUE TITLE
Calender comes in numerical format what to do?

### ISSUE THREAD

**Issue by roshanaale9818** [aavanzyl/ngx-tiny#2] opened 2020-05-06 18:03 UTC
![Screenshot_4](https://user-images.githubusercontent.com/48641698/81212023-f8aaf600-8ff3-11ea-87b8-82ca6fed4648.jpg)
I tried everything on my own.

**Comment by roshanaale9818** [comment] 2020-05-06 18:03
how can make this to normal calender"?

**Comment by roshanaale9818** [comment] 2020-05-06 18:12
![Screenshot_5](https://user-images.githubusercontent.com/48641698/81212872-47a55b00-8ff5-11ea-8cde-bd1fb2bbd65f.jpg)
it fires something like this whenever i click on input field

**Comment by aavanzyl** [comment] 2020-05-08 11:35
Hi @roshanaale9818 

Would you be able to provide me the following:
1. Your app.module.ts
2. The directive along with the tag related to the directive. It should look something like this:
```html
<input formControlName="singleDate"  [ngxDatePicker]="dateInstanceOne">
  <ngx-date-picker #dateInstanceOne [options]="singleDatePickerOptions">
</ngx-date-picker>
```

I will need to debug this a bit from my side and see if I can recreate the issue, any input you can provide like an example app that this happens on would help me a lot in finding and fixing the issue

**Comment by aavanzyl** [comment] 2020-08-18 06:35
Closing this issue due to not being able to reproduce

**Closed by aavanzyl** 2020-08-18 06:35 UTC
